# Generated by Django 3.2.18 on 2023-03-04 03:30

from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.django3_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_blogpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_django_jsonfield', jsoneditor.fields.django3_jsonfield.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=jsoneditor.fields.django3_jsonfield.JSONField(),
        ),
        migrations.CreateModel(
            name='TestSubModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_inline_json_field', jsoneditor.fields.django3_jsonfield.JSONField(blank=True, help_text='Test JSON editor for the django-jsonfield from https://github.com/bradjasper/django-jsonfield', null=True, verbose_name='Test JSON 2')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.testmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TestSubModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_inline_json_field', jsoneditor.fields.django3_jsonfield.JSONField(blank=True, help_text='Test JSON editor for the django-jsonfield from https://github.com/bradjasper/django-jsonfield', null=True, verbose_name='Test JSON 2')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.testmodel')),
            ],
        ),
    ]
