# Generated by Django 3.2.18 on 2023-03-04 06:25

from django.db import migrations
import jsoneditor.fields.django3_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=jsoneditor.fields.django3_jsonfield.JSONField(default=[{'type': 'Compound', 'value': {'Delay': {'type': 'Short', 'value': 277}, 'DisplayEntityHeight': {'type': 'Float', 'value': 3.6}, 'DisplayEntityScale': {'type': 'Float', 'value': 1.0}, 'DisplayEntityWidth': {'type': 'Float', 'value': 1.6}, 'EntityIdentifier': {'type': 'String', 'value': 'minecraft:zombie'}, 'MaxNearbyEntities': {'type': 'Short', 'value': 6}, 'MaxSpawnDelay': {'type': 'Short', 'value': 800}, 'MinSpawnDelay': {'type': 'Short', 'value': 200}, 'RequiredPlayerRange': {'type': 'Short', 'value': 16}, 'SpawnCount': {'type': 'Short', 'value': 4}, 'SpawnData': {'type': 'Compound', 'value': {'Properties': {'type': 'Compound', 'value': {}}, 'TypeId': {'type': 'String', 'value': 'minecraft:cow'}, 'Weight': {'type': 'Int', 'value': 1}}}, 'SpawnPotentials': {'type': 'List', 'value': {'type_List': 'Compound', 'value_List': [{'Properties': {'type': 'Compound', 'value': {}}, 'TypeId': {'type': 'String', 'value': 'minecraft:cow'}, 'Weight': {'type': 'Int', 'value': 1}}, {'Properties': {'type': 'Compound', 'value': {}}, 'TypeId': {'type': 'String', 'value': 'minecraft:pig'}, 'Weight': {'type': 'Int', 'value': 1}}, {'Properties': {'type': 'Compound', 'value': {}}, 'TypeId': {'type': 'String', 'value': 'minecraft:sheep'}, 'Weight': {'type': 'Int', 'value': 1}}]}}, 'SpawnRange': {'type': 'Short', 'value': 4}, 'id': {'type': 'String', 'value': 'MobSpawner'}, 'isMovable': {'type': 'Byte', 'value': 1}, 'x': {'type': 'Int', 'value': 2}, 'y': {'type': 'Int', 'value': -60}, 'z': {'type': 'Int', 'value': 0}}}]),
        ),
    ]
