# Generated by Django 3.2.18 on 2023-03-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20230304_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='choice',
        ),
    ]
