# Generated by Django 3.2.18 on 2023-03-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_blogpost_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
    ]
